### PR TITLE
CRUD Assessment Resource

### PR DESCRIPTION
**Pull request by Austrie**
Updated non/partially-working CRUD routes for assessment

### CODE REVIEW

**Review by Jeffchiucp — APPROVED** [review]
Looks okay to me.

**Review by Jeffchiucp — DISMISSED** [review]
Can you put back line 79 `app.delete('/assessments/:id/delete', (req, res) => {`   This is for consistency with all RESTFUL routes and controllers.  I would also add a Postman test cases for `Assessment DELETE` to the SERVER API

**Comment by Austrie** [comment]
@Jeffchiucp Tassos (@tlambrou) Agreed that it is RESTful since we signified that it's a delete through 'app.delete'. Though, you are right that the other delete routes in the project have '/delete'. So should we keep '/delete' for sake of consistency, or change the other files?

**Comment by Austrie** [comment]
@Jeffchiucp @tlambrou Pushed a new commit updating postman collection and removing '/delete' from end of delete routes.

**Comment by Jeffchiucp** [comment]
I see what @tlambrou and @Austrie did. Since we already use the HTTP verb `delete` then we can don't need the word `delete` in our Routes. I also include the reference to the RESourceful routes here:
https://www.notion.so/productcollege/Resourceful-Routes-55d6f3f46c064abeb718c94ca77ccf18

**Comment by tlambrou** [comment]
We can can also remove the “create” keyword in the backend routes as this is the only post method route.  Didn’t want to break the front end links though.

**Pull request merged**
