### PR TITLE
Got open graph working however, this approach executes an array of hu…

### PR DESCRIPTION
**Pull request by tlambrou**
…ndreds of promises and takes about 4-5 seconds locally to complete the fetching of all data for each learning action.  Will need to make the open graph call upon Action creation and save to the Action model as JSON datatype.

### CODE REVIEW

**Comment by tlambrou** [comment]
I'm going to keep this for now as I will be able to test the frontend UI now that it's working.

**Comment by tlambrou** [comment]
The 4-5 second delay will slow down our dashboard by the same amount since it hits the same route.  :(

**Comment by Jeffchiucp** [comment]
good point

**Review by Jeffchiucp — COMMENTED** [review]
needed to implement the feature set for open-graph protocol

**Pull request closed without merging**
